import { mkdtempSync, writeFileSync, mkdirSync, rmdirSync, unlinkSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { test } from "uvu";
import * as assert from "uvu/assert";
import { co2 } from "@tgwf/co2";
import {
	calculateBytes,
	buildCarbonTxt,
	type CloudflareAnalyticsResult,
} from "./index";

test("calculateBytes returns file size for a single file", async () => {
	const dir = mkdtempSync(join(tmpdir(), "co2js-"));
	const file = join(dir, "foo.txt");
	const content = "hello world";
	writeFileSync(file, content);
	try {
		const bytes = await calculateBytes(file);
		assert.equal(bytes, Buffer.byteLength(content));
	} finally {
		unlinkSync(file);
		rmdirSync(dir);
	}
});

test("calculateBytes returns total size for directory (ignores node_modules and .git)", async () => {
	const dir = mkdtempSync(join(tmpdir(), "co2js-"));
	const a = join(dir, "a.txt");
	const b = join(dir, "b.txt");
	const nodeModules = join(dir, "node_modules");
	const nodeModulesFile = join(nodeModules, "pkg.js");
	const gitDir = join(dir, ".git");
	const gitFile = join(gitDir, "HEAD");
	writeFileSync(a, "aa");
	writeFileSync(b, "bb");
	mkdirSync(nodeModules, { recursive: true });
	writeFileSync(nodeModulesFile, "ignored");
	mkdirSync(gitDir, { recursive: true });
	writeFileSync(gitFile, "ref");
	try {
		const bytes = await calculateBytes(dir);
		assert.equal(bytes, 4);
	} finally {
		unlinkSync(a);
		unlinkSync(b);
		unlinkSync(nodeModulesFile);
		rmdirSync(nodeModules);
		unlinkSync(gitFile);
		rmdirSync(gitDir);
		rmdirSync(dir);
	}
});

test("calculateBytes throws for non-existent path", async () => {
	try {
		await calculateBytes(join(tmpdir(), "does-not-exist-xyz"));
		assert.unreachable("should have thrown");
	} catch (err) {
		assert.match((err as Error).message, /Path not found/);
	}
});

test("buildCarbonTxt contains build section and correct values", () => {
	const emissions = new co2({ model: "1byte" });
	const out = buildCarbonTxt({
		bytes: 1000,
		greenHosting: true,
		estimatedCO2: 0.5,
		cloudflareAnalytics: null,
		emissions,
	});
	assert.match(out, /# Generated by CO2\.js GitHub Action/);
	assert.match(out, /\[build\]/);
	assert.match(out, /total_bytes = 1000/);
	assert.match(out, /green_hosting = true/);
	assert.match(out, /estimated_co2_grams = 0\.5/);
	assert.not.match(out, /\[cloudflare\]/);
});

test("buildCarbonTxt includes cloudflare section when analytics provided", () => {
	const emissions = new co2({ model: "1byte" });
	const cloudflare: CloudflareAnalyticsResult = {
		zone_id: "zone-1",
		time_range: { since: "2025-01-01", until: "2025-01-31" },
		totals: { requests: 100, bytes: 5000 },
		daily: [
			{ date: "2025-01-01", requests: 50, bytes: 2500 },
			{ date: "2025-01-02", requests: 50, bytes: 2500 },
		],
	};
	const out = buildCarbonTxt({
		bytes: 1000,
		greenHosting: false,
		estimatedCO2: 0.3,
		cloudflareAnalytics: cloudflare,
		emissions,
	});
	assert.match(out, /\[cloudflare\]/);
	assert.match(out, /zone_id = "zone-1"/);
	assert.match(out, /since = "2025-01-01"/);
	assert.match(out, /until = "2025-01-31"/);
	assert.match(out, /requests = 100/);
	assert.match(out, /bytes = 5000/);
	assert.match(out, /\[\[cloudflare\.daily\]\]/);
	assert.match(out, /date = "2025-01-01"/);
	assert.match(out, /date = "2025-01-02"/);
});

test.run();
