import * as core from '@actions/core';
import { co2 } from '@tgwf/co2';
import * as fs from 'fs';
import * as path from 'path';
import { glob } from 'glob';

async function run(): Promise<void> {
    try {
        const inputPath = core.getInput('path') || '.';
        const greenHosting = core.getInput('green-hosting') === 'true';
        const destination = core.getInput('destination') || '.';

        console.log(`Measuring size for path: ${inputPath}`);
        console.log(`Green hosting: ${greenHosting}`);
        console.log(`Destination: ${destination}`);

        const bytes = await calculateBytes(inputPath);
        console.log(`Total bytes: ${bytes}`);

        const emissions = new co2({ model: '1byte' });
        const estimatedCO2 = emissions.perByte(bytes, greenHosting);

        console.log(`Estimated CO2 emissions: ${estimatedCO2} grams`);
        core.setOutput('emissions', estimatedCO2);

        const carbonTxtContent = `
# Generated by CO2.js GitHub Action

[build]
date = "${new Date().toISOString()}"
total_bytes = ${bytes}
green_hosting = ${greenHosting}
estimated_co2_grams = ${estimatedCO2}
`.trim();

        // Ensure destination directory exists
        if (!fs.existsSync(destination)) {
            fs.mkdirSync(destination, { recursive: true });
        }

        const carbonTxtPath = path.join(destination, 'carbon.txt');
        fs.writeFileSync(carbonTxtPath, carbonTxtContent);
        console.log(`Created carbon.txt at ${carbonTxtPath}`);

    } catch (error) {
        if (error instanceof Error) core.setFailed(error.message);
    }
}

async function calculateBytes(targetPath: string): Promise<number> {
    let totalBytes = 0;

    // Check if path exists
    if (!fs.existsSync(targetPath)) {
        throw new Error(`Path not found: ${targetPath}`);
    }

    const stats = fs.statSync(targetPath);

    if (stats.isFile()) {
        return stats.size;
    }

    if (stats.isDirectory()) {
        const pattern = '**/*';
        const files = await glob(pattern, {
            cwd: targetPath,
            ignore: ['**/.git/**', '**/node_modules/**'],
            nodir: true,
            absolute: true
        });

        for (const file of files) {
            const fileStats = fs.statSync(file);
            totalBytes += fileStats.size;
        }
    }

    return totalBytes;
}

run();
